version: "3.8"

services:
  ghost:
    image: ghost:4-alpine
    restart: always
    env_file: .env
    ports:
      - "2368:2368"
    volumes:
      - ghost:/var/lib/ghost/content
      - ./theme:/var/lib/ghost/content/themes/theme

        #https_proxy:
        #image: nginx:1.21-alpine
        #restart: always
        #ports:
        #- "443:443"
        #- "80:80"
        #volumes:
        #- ./nginx.conf:/etc/nginx/nginx.conf
        #- /etc/letsencrypt/live/tommarx.fr-0001/fullchain.pem:/root/server.cert
        #- /etc/letsencrypt/live/tommarx.fr-0001/privkey.pem:/root/server.key
        #depends_on:
        #- ghost

  proxy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy:/data
    env_file: .env
    ports:
      - "80:80" # To complete HTTPS challenge
      - "443:443"

volumes:
  ghost:
  caddy:
