version: "3.8"

services:
  ghost:
    image: ghost:4-alpine
    restart: always
    env_file: .env
    ports:
      - "2368:2368"
    volumes:
      - ghost:/var/lib/ghost/content
      - ./theme:/var/lib/ghost/content/themes/theme

  https_proxy:
    image: nginx:1.21-alpine
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server.cert:/root/server.cert
      - ./server.key:/root/server.key
    depends_on:
      - ghost

volumes:
  ghost: